In [2]:
## Load libraries
import numpy as np
import sys
import matplotlib.pyplot as plt
import matplotlib.cm as cm
plt.style.use('dark_background')
%matplotlib inline

In [3]:
np.set_printoptions(precision=2)

In [4]:
import tensorflow as tf

In [5]:
tf.__version__

'2.15.0'

In [6]:
# Generate artificial data with 10 samples, 5 features per sample
# and 3 output classes
num_samples = 10 # number of samples
num_features = 5 # number of features (a.k.a. dimensionality)
num_labels = 3 # number of output labels
# Data matrix (each column = single sample)
X = np.random.choice(np.arange(3, 10), size = (num_features, num_samples), replace = True)
# Class labels
y = np.random.choice([0, 1, 2], size = num_samples, replace = True)
print(X)
print('------')
print(y)
print('------')
# One-hot encode class labels
y = tf.keras.utils.to_categorical(y).T
print(y)

[[4 7 7 6 5 5 8 6 6 5]
 [6 6 5 9 6 7 7 8 8 5]
 [4 4 4 7 7 5 3 3 5 6]
 [8 5 3 9 6 8 7 3 4 3]
 [3 8 6 4 6 8 7 7 4 8]]
------
[1 0 2 0 0 2 1 0 1 1]
------
[[0. 1. 0. 1. 1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
 [0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]]


---

A generic layer class with forward and backward methods

----

In [7]:
class Layer:
  def __init__(self):
    self.input = None
    self.output = None

  def forward(self, input):
    pass

  def backward(self, output_gradient, learning_rate):
    pass

---

The softmax classifier steps for a generic sample $\mathbf{x}$ with (one-hot encoded) true label $\mathbf{y}$ (3 possible categories) using a randomly initialized weights matrix (with bias absorbed as its last last column):

1. Calculate raw scores vector for a generic sample $\mathbf{x}$  (bias feature added): $$\mathbf{z} = \mathbf{Wx}.$$
2. Calculate softmax probabilities (that is, softmax-activate the raw scores) $$\mathbf{a} = \text{softmax}(\mathbf{z})\Rightarrow\begin{bmatrix}a_0\\a_1\\a_2\end{bmatrix}= \text{softmax}\left(\begin{bmatrix}z_0\\z_1\\z_2\end{bmatrix}\right)=\begin{bmatrix}\frac{e^{z_0}}{e^{z_0}+e^{z_1}+e^{z_2}}\\\frac{e^{z_1}}{e^{z_0}+e^{z_1}+e^{z_2}}\\\frac{e^{z_2}}{e^{z_0}+e^{z_1}+e^{z_2}}\end{bmatrix}$$
3. Softmax loss for this sample is (where output label $y$ is not yet one-hot encoded)
$$\begin{align*}L &=  -\log([\mathbf{a}]_y) \\&= -\log\left(\left[\text{softmax}(\mathbf{z})\right]_y\right)\\ &= -\log\left(\left[\text{softmax}(\mathbf{Wx})\right]_y\right).\end{align*}$$
4. Predicted probability vector that the sample belongs to each one of the output categories is given a new name $$\hat{\mathbf{y}} = \mathbf{a}.$$
5. One-hot encoding the output label $$\underbrace{y\rightarrow\mathbf{y}}_{\text{e.g.}\,2\,\rightarrow\begin{bmatrix}0\\0\\1\end{bmatrix}}$$ results in the following representation for the softmax loss for the sample which is also referred to as the categorical crossentropy (CCE) loss:
$$\begin{align*}L &= L\left(\mathbf{y},\hat{\mathbf{y}}\right)=\sum_{k=0}^2-y_k\log\left(\hat{y}_k\right)=-\mathbf{y}^\mathrm{T}\log\left(\hat{\mathbf{y}}\right)\end{align*}.$$
5. Calculate the gradient of the loss for the sample w.r.t. weights by following the computation graph from top to bottom (that is, backward):
$$\begin{align*} L\\{\color{yellow}\downarrow}\\ \hat{\mathbf{y}} &= \mathbf{a}\\{\color{yellow}\downarrow}\\\mathbf{z}\\{\color{yellow}\downarrow}\\\mathbf{W},\mathbf{x}\end{align*}$$

$$\begin{align*}\Rightarrow \nabla_\mathbf{W}(L) &= \nabla_\mathbf{W}(\mathbf{z}) \times\nabla_\mathbf{z}(\hat{\mathbf{y}})\times\nabla_{\hat{\mathbf{y}}}(L)\\&= \underbrace{\nabla_\mathbf{W}(\mathbf{z})}_\text{first term} \times\underbrace{\nabla_\mathbf{z}(\mathbf{a})}_\text{second to last term}\times\underbrace{\nabla_\hat{\mathbf{y}}(L)}_\text{last term}.\end{align*}$$Gradient descent step:
$$\mathbf{W} = \mathbf{W}+\alpha\times\left(-\nabla_\mathbf{W}(L)\right).$$
7. Now focus on the last term $\nabla_\hat{\mathbf{y}}(L)$:
$$\begin{align*}\nabla_\hat{\mathbf{y}}(L) &=\begin{bmatrix}\nabla_{\hat{y}_0}(L)\\\nabla_{\hat{y}_1}(L)\\\nabla_{\hat{y}_2}(L)\end{bmatrix} = \begin{bmatrix}-y_0/\hat{y}_0\\-y_1/\hat{y}_1\\-y_2/\hat{y}_2\end{bmatrix}.\end{align*}$$
8. Now focus on the second to last term $\nabla_\mathbf{z}(\mathbf{a})$:
$$\begin{align*}\nabla_\mathbf{z}(\mathbf{a}) &= \nabla_\mathbf{z}\left(\begin{bmatrix}a_0\\a_1\\a_2\end{bmatrix}\right)\\ &= \begin{bmatrix}\nabla_\mathbf{z}(a_0)&\nabla_\mathbf{z}(a_1)&\nabla_\mathbf{z}(a_2)\end{bmatrix} \\&= \begin{bmatrix}\nabla_{z_0}(a_0)&\nabla_{z_0}(a_1)&\nabla_{z_0}(a_2)\\\nabla_{z_1}(a_0)&\nabla_{z_1}(a_1)&\nabla_{z_1}(a_2)\\\nabla_{z_2}(a_0)&\nabla_{z_2}(a_1)&\nabla_{z_2}(a_2)\end{bmatrix}\\&=\begin{bmatrix}a_0(1-a_0)&-a_1a_0&-a_2a_0\\-a_0a_1&a_1(1-a_1)&-a_2a_1\\-a_0a_2&-a_1a_2&a_2(1-a_2)\end{bmatrix}.\end{align*}$$
9. Now focus on the last term $\nabla_\mathbf{W}(\mathbf{z}) = \nabla_\mathbf{W}(\mathbf{Wx})$:

![](https://onedrive.live.com/embed?resid=37720F927B6DDC34%21103155&authkey=%21AMH79mXBdb_raAA&width=660)

The full gradient can be written as $\nabla_\mathbf{W}(L)=$

![](https://onedrive.live.com/embed?resid=37720F927B6DDC34%21103156&authkey=%21AIdyOQ3a-er-7-A&width=660)

$$\begin{align*}=\begin{bmatrix}a_1(1-a_1)&-a_2a_1&-a_3a_1\\-a_1a_2&a_2(1-a_2)&-a_3a_2\\-a_1a_3&-a_2a_3&a_3(1-a_3)\end{bmatrix}\times\begin{bmatrix}-y_1/\hat{y}_1\\-y_2/\hat{y}_2\\-y_3/\hat{y}_3\end{bmatrix}\mathbf{x}^\mathrm{T}.\end{align*}$$


---

---

CCE loss and its gradient

$$\begin{align*}L &= L\left(\mathbf{y},\hat{\mathbf{y}}\right)=\sum_{k=0}^2-y_k\log\left(\hat{y}_k\right) = -\mathbf{y}^\mathrm{T}\log\left(\hat{\mathbf{y}}\right)\\\nabla_\hat{\mathbf{y}}(L) &=\begin{bmatrix}\nabla_{\hat{y}_0}(L)\\\nabla_{\hat{y}_1}(L)\\\nabla_{\hat{y}_2}(L)\end{bmatrix} = \begin{bmatrix}-y_0/\hat{y}_0\\-y_1/\hat{y}_1\\-y_2/\hat{y}_2\end{bmatrix}.\end{align*}$$


---

In [8]:
## Define the loss function and its gradient
def cce(y, yhat):
  return(-np.sum(y*np.log(yhat)))
  #return(np.dot(-y, np.log(yhat)))

def cce_gradient(y, yhat):
  return(-y/yhat)

# TensorFlow in-built function for categorical crossentropy loss
#cce = tf.keras.losses.CategoricalCrossentropy()

---

Softmax activation layer class
$$\begin{align*}\text{forward:}\ \mathbf{a} &=\text{softmax}(\mathbf{z}),\\\text{backward:}\ \nabla_\mathbf{z}(L) &= \nabla_{\mathbf{z}}(\mathbf{a})\times\nabla_{\mathbf{a}}(L) = \nabla_{\mathbf{z}}(\mathbf{a})\times\nabla_{\hat{\mathbf{y}}}(L)\\&=\begin{bmatrix}a_0(1-a_0)&-a_1a_0&-a_2a_0\\-a_0a_1&a_1(1-a_1)&-a_2a_1\\-a_0a_2&-a_1a_2&a_2(1-a_2)\end{bmatrix}\begin{bmatrix}-y_0/\hat{y}_0\\-y_1/\hat{y}_1\\-y_2/\hat{y}_2\end{bmatrix}.\end{align*}$$


---

In [9]:
z = np.array([-1., 2., 3.])
tf.nn.softmax(z).numpy()

array([0.01, 0.27, 0.72])

In [10]:
## Softmax activation layer class
class Softmax(Layer):
  def forward(self, input):
    self.output = tf.nn.softmax(input).numpy()

  def backward(self, output_gradient, learning_rate = None):
    return(np.dot((np.identity(np.size(self.output))-self.output.T) * self.output, output_gradient))

---

Dense layer class

$$\begin{align*}\text{forward:}\ \mathbf{z}&=\mathbf{Wx}\\\text{backward:}\ \nabla_\mathbf{W}(L)&=\nabla_{\mathbf{W}}(\mathbf{z})\times\nabla_{\mathbf{z}}(L)\\&=\nabla_{\mathbf{z}}(L)\mathbf{x}^\mathrm{T}.\end{align*}$$

---

In [11]:
np.empty((3, 5+1), dtype = np.float64)

array([[6.80e-310, 6.80e-310, 4.73e-310, 4.73e-310, 4.94e-324, 4.73e-310],
       [4.73e-310, 1.19e-322, 6.80e-310, 4.24e-314, 5.81e-321, 4.94e-324],
       [4.24e-314, 1.04e-322, 4.73e-310, 6.80e-310, 6.80e-310, 4.94e-324]])

In [12]:
np.random.randn(3, 5)

array([[ 0.25,  0.08,  0.22, -0.13, -0.83],
       [ 0.64,  1.5 ,  1.43,  0.43, -0.47],
       [ 0.37, -0.77, -0.55, -1.04, -0.18]])

In [13]:
## Dense layer class
class Dense(Layer):
    def __init__(self, input_size, output_size):
        self.weights = np.empty((output_size, input_size+1), dtype = np.float64) # bias trick
        # Initializing the weights part of the weights matrix
        self.weights[:, :-1] = 0.01 * np.random.randn(output_size, input_size)
        self.weights[:, -1] = 0.01 # Set all bias values to the same nonzero constant

    def forward(self, input):
        self.input = np.append(input, 1) # adding the bias feature 1
        self.output = np.dot(self.weights, self.input)

    def backward(self, output_gradient, learning_rate):
        weights_gradient = np.dot(output_gradient.reshape(-1, 1), self.input.reshape(-1, 1).T)
        input_gradient = np.dot(self.weights.T, output_gradient)
        self.weights = self.weights + learning_rate * (-weights_gradient)
        return input_gradient

In [14]:
# Forward and backward propagation for the 0th sample
learning_rate = 1e-02

# Define the neural network architecture
dlayer = Dense(num_features, num_labels) # define the dense layer
#print(dlayer.weights)
softmax = Softmax() # define the softmax activation layer
print(dlayer.weights)

# Forward propagation starts here
dlayer.forward(X[:, 0]) # forward prop for the 0th sample
softmax.forward(dlayer.output)
loss = cce(y[:, 0], softmax.output)
#print(loss)

# Backward propagation starts here
grad = cce_gradient(y[:, 0], softmax.output)
grad = softmax.backward(grad)
grad = dlayer.backward(grad, learning_rate)
print('-----')
print(dlayer.weights)

[[-5.86e-03  1.35e-05 -3.30e-03  6.90e-03 -1.63e-02  1.00e-02]
 [ 1.28e-02 -1.30e-02 -6.91e-03 -1.59e-02 -1.13e-02  1.00e-02]
 [ 9.99e-03 -3.08e-03 -2.57e-04 -7.60e-03 -7.50e-03  1.00e-02]]
-----
[[-0.02 -0.02 -0.02 -0.02 -0.03  0.01]
 [ 0.04  0.03  0.02  0.04  0.01  0.02]
 [-0.   -0.02 -0.01 -0.03 -0.02  0.01]]


In [15]:
## Train the 0-layer neural network using batch training with batch size = 1

# Steps: run over each sample, calculate loss, gradient of loss,
# and update weights.

# Forward and backward propagation for the 0th sample
learning_rate = 1e-02

# Define the neural network architecture
dlayer = Dense(num_features, num_labels) # define the dense layer
#print(dlayer.weights)
softmax = Softmax() # define the softmax activation layer

loss = 0.0

for i in range(X.shape[1]):
  # Forward propagation starts here
  dlayer.forward(X[:, i]) # forward prop for the 0th sample
  softmax.forward(dlayer.output)
  loss = cce(y[:, i], softmax.output)

  # Backward propagation starts here
  grad = cce_gradient(y[:, i], softmax.output)
  grad = softmax.backward(grad)
  grad = dlayer.backward(grad, learning_rate)

  print('Sample %d, loss = %f'%(i, loss))



Sample 0, loss = 1.117076
Sample 1, loss = 2.017570
Sample 2, loss = 2.048463
Sample 3, loss = 1.081890
Sample 4, loss = 0.201609
Sample 5, loss = 4.424825
Sample 6, loss = 4.449116
Sample 7, loss = 0.297289
Sample 8, loss = 3.570937
Sample 9, loss = 2.238735
